# Generated by Django 3.2.9 on 2022-01-30 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_string', models.CharField(max_length=1024, null=True)),
                ('master_answer', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_name', models.CharField(max_length=1024)),
                ('created_by_user', models.CharField(max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by_user', models.CharField(max_length=1024, null=True)),
                ('is_true', models.BooleanField(default=False)),
                ('user_answer', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pubquiz.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pubquiz.quiz'),
        ),
    ]
