# Generated by Django 3.2.9 on 2022-01-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_string', models.CharField(max_length=1024, null=True)),
                ('master_answer', models.CharField(max_length=1024, null=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pubquiz.quiz')),
            ],
        ),
    ]
