# Generated by Django 3.2.9 on 2022-01-16 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pubquiz', '0003_alter_question_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_answer', models.CharField(max_length=1024)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pubquiz.question')),
            ],
        ),
    ]
