# Generated by Django 3.2.9 on 2022-01-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pubquiz', '0006_alter_useranswer_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_by_user',
        ),
        migrations.AddField(
            model_name='quiz',
            name='created_by_user',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
